export const actionType = {
    SET_MOVIE_LIST: "SET_MOVIE_LIST",
    SET_MOVIE_DETAIL: "SET_MOVIE_DETAIL",
    SET_MOVIE_BANNER: "SET_MOVIE_BANNER",
    SET_MOVIE_CINEMA: "SET_MOVIE_CINEMA",
    SET_TICKET_DETAIL: "SET_TICKET_DETAIL",
    SET_ME: "SET_ME",
    SET_ACCOUNT_INFOR: "SET_ACCOUNT_INFOR",
    SET_CINEMA_LIST_SEAT: "SET_CINEMA_LIST_SEAT",
}